[paths]
gearshifft_root    = "../gearshifft"             # root of gearshifft repo relative to GearshifftEvaluation root dir
output_dir         = "output/"                   # default place to store program outputs (plots etc.)
cache_dir          = ".cache/"                   # default place to cache information