[base]
cmake_inherits = ["default"] # REQUIRED: base preset in <benchmark root>/CMakePresets.json
# Build Settings - mapping to CMake cache variables in config.toml
double = "ON"
float = "ON"
test_my_version = "ON" # Use my fork of eigen
kissfft = "OFF"
pocketfft = "OFF"
fftw = "OFF"
mkl = "OFF"
cache_vars     = {} # Any other CMake cacheVariables as Pairs, e.g. {CMAKE_C_COMPILER = "gcc", ...}
# Runtime Settings
extents        = ["test.conf"]
real           = true  # run r2c/c2r benchmarks
complex        = true  # run c2c benchmarks
reps = 10

[test-fftwd]
inherits = "base"
implementation = "fftwd"
fftw = "ON"
[test-fftwf]
inherits = "test-fftwd"
implementation = "fftwf"

[test-kissfftd]
inherits = "base"
implementation = "kissfftd"
kissfft = "ON"
[test-kissfftf]
inherits = "test-kissfftd"
implementation = "kissfftf"