[base]
# Basics
x_scale = "log"                     # Possible values: "log", "linear"
x_dir   = "normal"                  # Possible values: "normal", "reverse"
y_scale = "log"                     # Possible values: "log", "linear"
y_dir   = "normal"                  # Possible values: "normal", "reverse"
x_log_basis = 2
y_log_basis = 10
x_label = "[Bytes]"                 # Label for the x-axis
y_label = "L2 Error"                    # Label for the y-axis

# Benchmark output selection
benchmark_templates = []           # List sets of benchmarks to compare, e.g. ["benchA", "benchB"]
csv_count_per_benchmark = 1        # Number of CSV files to include for each benchmark template (<= 0 for max available)
group_by_columns = ["dim","complex"] # Which csv columns to group by besides x_values
                                                                     # for aggregation (see output csv for all options)
meta_data_labels = ["backend", "precision", "Threads"]                                       # Which values from the output csv header to add to series labels
x_values = ["size_bytes"]                    # Which values to plot against (1D only atm)
y_values = ["err_L2_norm"] # Which values to plot ("Time_Allocation_ms","Time_PlanInitFwd_ms",
                                                            # "Time_PlanInitInv_ms","Time_Upload_ms","Time_FFT_ms","Time_iFFT_ms",
                                                            # "Time_Download_ms","Time_PlanDestroy_ms","Time_Total_ms",
                                                            # "Error_StandardDeviation", "Error_Mismatches")
scatter = true

# Data processing
row_filter = {}         # Filter out rows that contain the value at column key
fail_warn = {}         # Produce a warning if a row contains this value at column key
combine_same_benchmark_data = true        # Use true to merge data from the same benchmark into one curve
aggregation_function = "mean"             # Possible choices: "mean", "median", "min", "max"
error_bar_method = "none"                 # Possible choices: "std_dev", "quantiles", "max_dev", "none"
quantile_low = 0.1                        # Lowest quantile for quantiles error_bar_method
quantile_high = 0.9                       # Highest quantile for quantiles error_bar_method
x_transform = "none"                      # Optional transform of the x-axis (currently just 'B_to_MiB')
y_transform = "none"                      # Optional transform of the measured data on the y-axis
                                          # (currently just 'fft_perf' to compute FFT performance)

[double-accuracy-all-prime-complex]
inherits = "base"
row_filter = {complex = "Complex"}
benchmark_templates = ["eigen-kissfft-prime", "eigen-pocketfft-prime", "eigen-mkl-prime", "eigen-fftw-prime"]