[base]
cmake_inherits = ["release"] # REQUIRED: base preset in gearshifft/CMakePresets.json
# Build Settings - mapping to CMake cache variables in config.toml
nr_warmup      = 2
nr_warm_runs   = 10
error_bound    = -1 # -1 for dynamic error bound within gearshifft
dump_frequency = 1  # Number of benchmarks results to collect before dumping to backup file
llc_mib        = 32 # Size of the processor's last level cache in MiB
cl_mb          = 64 # Size of the processor's cache Lines in B
test_my_version = "ON" # Use my fork of eigen
cache_vars     = {} # Any other CMake cacheVariables as Pairs, e.g. {CMAKE_C_COMPILER = "gcc", ...}
# Runtime Settings
extents        = [] # gearshifft extents files (row-wise csv)
verbose        = false
device         = "cpu" # (gpu|cpu|acc|<ID>)
nr_devices     = 1  # parallelism if supported, 0 = all
inplace        = true  # run inplace benchmarks
outplace       = true  # run outplace benchmarks
real           = true  # run r2c/c2r benchmarks
complex        = true  # run c2c benchmarks
precision      = "all" # which precisions to benchmark
                       # (options depend on implementation, typically ("double"|"float"))

[test-fftw]
inherits = "base"
implementation = "fftw"
extents = ["test.conf"]

[test-eigen-fftw]
inplace = false
inherits = "test-fftw"
implementation = "eigen_fftw"

[test-fftw-outplace-complex-double]
inherits = "test-fftw"
inplace = false
real = false
precision = "double"

[test-eigen-fftw-outplace-complex-double]
inherits = "test-fftw-outplace-complex-double"
implementation = "eigen_fftw"

[test-fftw-plan-estimate]
inherits = "test-fftw"
plan_rigor = "estimate"