[base]
# Basics
x_scale = "log"                     # Possible values: "log", "linear"
x_dir   = "normal"                  # Possible values: "normal", "reverse"
y_scale = "log"                     # Possible values: "log", "linear"
y_dir   = "normal"                  # Possible values: "normal", "reverse"
x_log_basis = 2
y_log_basis = 10
x_label = "[MiB]"                   # Label for the x-axis
y_label = "[ms]"                    # Label for the y-axis

# Benchmark output selection
benchmark_templates = []           # List sets of benchmarks to compare, e.g. ["benchA", "benchB"]
csv_count_per_benchmark = 1        # Number of CSV files to include for each benchmark template (<= 0 for max available)
group_by_columns = ["library","inplace","complex","precision","dim"] # Which csv columns to group by besides x_values
                                                                     # for aggregation (see output csv for all options)
x_values = ["Size_DeviceTransfer_bytes"]                    # Which values to plot against (1D only atm)
y_values = ["Time_FFT_ms", "Time_iFFT_ms", "Time_Total_ms"] # Which values to plot ("Time_Allocation_ms","Time_PlanInitFwd_ms",
                                                            # "Time_PlanInitInv_ms","Time_Upload_ms","Time_FFT_ms","Time_iFFT_ms",
                                                            # "Time_Download_ms","Time_PlanDestroy_ms","Time_Total_ms",
                                                            # "Error_StandardDeviation", "Error_Mismatches")

# Data processing
combine_same_benchmark_data = true        # Use true to merge data from the same benchmark into one curve
aggregation_function = "mean"             # Possible choices: "mean", "median", "min", "max"
error_bar_method = "none"                 # Possible choices: "std_dev", "quantiles", "max_dev", "none"
x_transform = "none"                      # Optional transform of the x-axis (currently just 'B_to_MiB')
y_transform = "none"                      # Optional transform of the measured data on the y-axis
                                          # (currently just 'flops_per_ms' to compute FFT peak performance)

[test]
inherits = "base"
benchmark_templates = ["test-eigen-fftw-outplace-complex-double", "test-fftw-outplace-complex-double"]
csv_count_per_benchmark = 2
combine_same_benchmark_data = true
y_values = ["Time_FFT_ms", "Time_iFFT_ms"]