using TOML
using JSON3
using OrderedCollections
using SHA
using Dates

get_hash(preset::OrderedDict) = bytes2hex(sha256(JSON3.write(preset)))

function cmake_preset_from_template(toml_data::Dict, name::String)
    template = get_template(toml_data, name)
    try
        new_preset = 
            OrderedDict( # name and build variables: need to be defined in base preset
                "name" => name,
                "displayName" => "Generated by GearshifftEvaluation from '$name' template",
                "inherits" => template["cmake_inherits"],
                "cacheVariables" => OrderedDict{String, Any}(
                    "GEARSHIFFT_NUMBER_WARMUPS"    => template["nr_warmup"],
                    "GEARSHIFFT_NUMBER_WARM_RUNS"  => template["nr_warm_runs"],
                    "GEARSHIFFT_ERROR_BOUND"       => template["error_bound"],
                    "GEARSHIFFT_DUMP_FREQUENCY"    => template["dump_frequency"],
                    "GEARSHIFFT_LLC_SIZE_MIB"      => template["llc_mib"],
                    "GEARSHIFFT_CACHE_LINE_SIZE_B" => template["cl_mb"]
                )
            )
        # Merge additional cache variables if present
        if haskey(template, "cache_vars")
            merge!(new_preset["cacheVariables"], 
                    template["cache_vars"])
        end
        
        # Convert all cache variables to String
        for (key, value) in new_preset["cacheVariables"]
            new_preset["cacheVariables"][key] = string(value)
        end

        return new_preset
    catch e
        error("CMake Preset generation failed: $e")
    end
end

function generate_cmake_userpreset(toml_template_file::String, benchmark_template::String, path::String)
    # Check if CMakePresets.json exists in path already
    if !isfile(joinpath(path, "CMakePresets.json"))
        @error "Tried to add a CMake user preset to $path but CMakePresets.json from gearshifft root does not exist"
    end

    # Create CMake preset structure
    toml_data = TOML.parsefile(toml_template_file)
    new_preset = cmake_preset_from_template(toml_data, benchmark_template)
    
    # Add hash key as comment for unique id
    hash_key = get_hash(new_preset)
    push!(new_preset, "\$comment" => hash_key)

    # Write to CMakeUserPresets.json
    output_path = joinpath(path, "CMakeUserPresets.json")

    # Initialize or load existing CMakeUserPresets.json
    cmake_presets = if isfile(output_path)
        # Load existing presets
        existing_presets = JSON3.read(read(output_path, String), OrderedDict{String, Any})
        
        # Check if this preset already exists
        if haskey(existing_presets, "configurePresets")
            preset_idx = findfirst(p -> p["name"] == benchmark_template, existing_presets["configurePresets"])
            if !isnothing(preset_idx)
                existing_preset = existing_presets["configurePresets"][preset_idx]
                if existing_preset["\$comment"] != new_preset["\$comment"] # comment contains SHA
                    @info "Preset '$benchmark_template' already exists in cached CMakeUserPresets.json. Overwriting."
                    existing_presets["configurePresets"][preset_idx] = new_preset
                else
                    return hash_key # nothing new to write
                end
            else
                push!(existing_presets["configurePresets"], new_preset)
            end
        else
            existing_presets["configurePresets"] = [new_preset]
        end

        existing_presets
    else
        @info "No CMakeUserPresets.json, creating new one..."
        OrderedDict(
            "\$schema" => "https://raw.githubusercontent.com/Kitware/CMake/refs/tags/v3.31.5/Help/manual/presets/schema.json",
            "version" => 10,
            "cmakeMinimumRequired" => OrderedDict(
                "major" => 3,
                "minor" => 31,
                "patch" => 0
            ),
            "configurePresets" => [new_preset]
        )
    end

    # Write updated presets to file (if cmake_presets isn't nothing)
    open(output_path, "w") do io
        JSON3.pretty(io, cmake_presets)
    end

    # Return hash key
    return hash_key
end

function cmake_config(preset_name::String, path::String, log_path::String="$(dirname(path))")
    # Run CMake
    @info "Configuring CMake with benchmark template '$preset_name'"
    log_file = joinpath(log_path, "cmake_config_logs", "$(preset_name)-$(now()).log")
    run_command_from_path(`cmake --preset $preset_name`, log_file, path)
end

function cmake_build(preset_name::String, path::String, bin_path::String, log_path::String="$(dirname(path))")
    if isdir(bin_path)
        @info "Suitable build for benchmark template '$preset_name' already found. Skipping build"
        return
    else
        mkpath(joinpath(bin_path))
    end
    # Run Generator through CMake
    @info "Building with benchmark template '$preset_name'"
    log_file  = joinpath(log_path, "cmake_build_logs", "$(preset_name)-$(now()).log")

    run_command_from_path(`cmake --build build/$preset_name`, log_file, path)
    cp(joinpath(path, "build", preset_name, "gearshifft"), bin_path, force=true)
end

function build(benchmark_template::String, gearshifft_root::AbstractString,
               cache_dir::AbstractString, benchmark_templates_dir::AbstractString)
    preset_name = benchmark_template

    # Symlink gearshifft root if not already done
    gearshifft_path = joinpath(cache_dir, "gearshifft")
    if !isdir(gearshifft_path)
        @info "Creating symlink to '$gearshifft_root'"
        symlink(gearshifft_root, gearshifft_path, dir_target = true)
    end

    hash_key = generate_cmake_userpreset(benchmark_templates_dir, preset_name, gearshifft_path)
    cmake_config(preset_name, gearshifft_path)
    cmake_build(preset_name, gearshifft_path, joinpath(cache_dir, hash_key))

    return hash_key
end