using JSON3
using OrderedCollections
using SHA
using Dates

get_hash(preset::OrderedDict) = bytes2hex(sha256(JSON3.write(preset)))

function cmake_preset_from_template(template::Dict, name::String)
    new_preset = try
        OrderedDict(
            "inherits" => template["cmake_inherits"],
            "cacheVariables" => OrderedDict{String, Any}(
                "GEARSHIFFT_NUMBER_WARMUPS"    => template["nr_warmup"],
                "GEARSHIFFT_NUMBER_WARM_RUNS"  => template["nr_warm_runs"],
                "GEARSHIFFT_ERROR_BOUND"       => template["error_bound"],
                "GEARSHIFFT_DUMP_FREQUENCY"    => template["dump_frequency"],
                "GEARSHIFFT_LLC_SIZE_MIB"      => template["llc_mib"],
                "GEARSHIFFT_CACHE_LINE_SIZE_B" => template["cl_mb"]
            )
        )
    catch e
        @error "Benchmark template '$name' doesn't specify or inherit all build variables:"
        showerror(stdout, e)
        exit(1)
    end
    # Merge additional cache variables if present
    if haskey(template, "cache_vars")
        merge!(new_preset["cacheVariables"], 
                template["cache_vars"])
    end
    
    # Convert all cache variables to String
    for (key, value) in new_preset["cacheVariables"]
        new_preset["cacheVariables"][key] = string(value)
    end
    
    # Compute build hash and use it as CMake Preset name
    hash = get_hash(new_preset)
    new_preset["name"] = hash
    new_preset["displayName"] = "Generated by GearshifftEvaluation from '$name' template"

    return new_preset
end

function generate_cmake_userpreset(template::Dict, name::String, path::String)
    # Check if CMakePresets.json exists in path already
    if !isfile(joinpath(path, "CMakePresets.json"))
        @error "Tried to add a CMake user preset to $path but CMakePresets.json from gearshifft root does not exist"
    end

    # Create CMake preset structure
    new_preset = cmake_preset_from_template(template, name)
    new_preset_hash = new_preset["name"]

    # Write to CMakeUserPresets.json
    output_path = joinpath(path, "CMakeUserPresets.json")

    # Initialize or load existing CMakeUserPresets.json
    cmake_presets = if isfile(output_path)
            # Load existing presets
            existing_presets = JSON3.read(read(output_path, String), OrderedDict{String, Any})
            
            # Check if this preset already exists
            if haskey(existing_presets, "configurePresets")
                if any(preset -> preset["name"] == new_preset_hash, existing_presets["configurePresets"])
                    @info "Found suitable preset for '$name' in CMakeUserPresets.json"
                else
                    push!(existing_presets["configurePresets"], new_preset)
                end
            else
                existing_presets["configurePresets"] = [new_preset]
            end

            existing_presets
        else
            @info "No CMakeUserPresets.json, creating new one..."
            OrderedDict(
                "\$schema" => "https://raw.githubusercontent.com/Kitware/CMake/refs/tags/v3.31.5/Help/manual/presets/schema.json",
                "version" => 10,
                "cmakeMinimumRequired" => OrderedDict(
                    "major" => 3,
                    "minor" => 31,
                    "patch" => 0
                ),
                "configurePresets" => [new_preset]
            )
        end

    # Write updated presets to file (if cmake_presets isn't nothing)
    open(output_path, "w") do io
        JSON3.pretty(io, cmake_presets)
    end

    # Return hash key
    return new_preset_hash
end

function cmake_config(preset_name::String, preset_hash::String, path::String, log_path::String="$(dirname(path))")
    # Run CMake
    @info "Configuring CMake with benchmark template '$preset_name'"
    log_file = joinpath(log_path, "cmake_config_logs", "$(preset_name)-$(now()).log")
    run_command_from_path(`cmake --preset $preset_hash`, log_file, path)
end

function cmake_build(preset_name::String, preset_hash::String, cache_dir::String,
                     path::String, log_path::String=cache_dir)
    bin_path = joinpath(cache_dir, preset_hash)
    mkpath(joinpath(bin_path))
    # Run Generator through CMake
    @info "Building with benchmark template '$preset_name'"

    log_file  = joinpath(log_path, "cmake_build_logs", "$(preset_name)-$(now()).log")

    run_command_from_path(`cmake --build build/$preset_hash`, log_file, path)
    cp(joinpath(path, "build", preset_hash, "gearshifft"), bin_path, force=true)
end

function build(template::Dict, name::String, gearshifft_root::AbstractString, cache_dir::AbstractString)
    # Symlink gearshifft root if not already done
    gearshifft_path = joinpath(cache_dir, "gearshifft")
    if !isdir(gearshifft_path)
        @info "Creating symlink to '$gearshifft_root'"
        symlink(gearshifft_root, gearshifft_path, dir_target = true)
    end

    preset_hash = generate_cmake_userpreset(template, name, gearshifft_path)
    cmake_config(name, preset_hash, gearshifft_path)
    cmake_build(name, preset_hash, cache_dir, gearshifft_path)

    return preset_hash
end